import Head from 'next/head'

// include them inside head
export default function HeadCommon(props) {
    const {pageTitle} = props;
    return (
        <Head>
            <title>{pageTitle}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}